togoid/togoid-converter

components/Databases.js, lib/setting.js
datasetをカテゴリ指定でフィルタ出来るようにする
現時点では元に戻すボタンのデザインが未完成です
color legend での絞り込みが必要になれば別途作成します
=> datasetのフィルタ

components/ResultModalAction.js
=> resultの先頭表示をIDにする

components/Explore.js
Exploreで要素を並び替える機能の実装
- buttonのUI
- 大元のオブジェクトごと並び替えているので、navigateに移行時にも反映されてしまう
- 実装が雑
=> [WIP]並び替えの実装

components/Explore.js
とりあえずドロップダウンと矢印のボタンに分けて実装している
マークアップお願いします
=> [WIP]ソート選択UIの変更

components/Explore.js
- `Source Count` `Target Count` を `Source count` `Target count` と `count` を小文字に変更
- `Sort by` という表示を追加
- `Sort by` とドロップダウンの間に隙間あった方が良い感じでしょうか？
=> ソート関連の表示変更

components/Explore.js, components/Navigate.js, components/ResultModalAction.js, components/ResultModalClipboardButton.js, lib/util.js, pages/index.js, styles/_input.scss
APIに新たに追加された`reduced`オプションに基づいてフロント側でファイルをダウンロードしたり、クリップボードにコピーしたりできるようにしました。
=> reducedオプションを使ってダウンロードできるようにする

components/Explore.js, components/Navigate.js, components/ResultModalAction.js, hooks/useResultModalPreview.js, lib/util.js
=> compactオプションのプレビューを表示する

components/Databases.js, components/Explore.js, components/InformationModal.js, components/Navigate.js, hooks/useConfig.js, pages/index.js, styles/_common.scss, styles/_input.scss
=> statisticのcountをlinkToに表示する

styles/_table.scss
=> Compactモードの時にテーブル内のIDを上揃え表示にする

styles/_index.scss
ヘッダーを考慮しつつ、アンカーリンクのジャンプが行えるように修正しました。
=> datasetのアンカーリンクのジャンプ位置を修正

components/Explore.js, styles/_index.scss
ascとdescでactiveになっている向きのボタンの色を変化するようにしました。
=> 並び替えのボタンの色を変化させる

components/Explore.js, styles/_index.scss
デフォルトの矢印の向きを変更し、ボタンをトグルに変更しました
=> Exploreでのsortのデフォルトの矢印の向きの調整とトグルへの変更

.eslintrc.json, @types/types.d.js, components/Annotate.js, hooks/useAnnotate.js, jsconfig.json
annotateの取得結果にlabelを付けました
その他変更は別途行います
JSDocの読み込みのために`jsconfig.json`を作成しています
=> annotateの取得データにlabelを付ける

components/Databases.js
=> dataset検索で大文字小文字の区別を無くし、categoryとtextで同時検索可能にする

components/Databases.js, jsconfig.json, styles/_index.scss, styles/_mixin.scss
- 各テキストにactiveというクラスをベタ打ちで付与しています。
activeクラスが取れるとテキストの色が薄くなるようになっています。
- リセットボタンのデザインをXDに合わせました。
- 四角の箇所のcheckedの時のスタイルは削除しました。
ご確認と後の処理をお願いします。
=> Color legend のレイアウト調整

src/components/LabelToId.tsx
=> label resolver の key を relations に dictionaries に変更しておく

src/components/Header.tsx, src/styles/foundation/_header.scss
resolved #122
全てのリンクが新規タブで展開するのか不明だったため、リンクタグに`target="_blank"`が設定されているときのみアイコンを表示するようにしました。
=> #122対応：ニュースリンクの追加

src/components/HeaderNews.tsx, src/styles/foundation/_header.scss
=> #127対応：ニュース一覧の調整

src/components/Datasets.tsx
=> DATASETS内の頭文字による遷移を検索に変更する

src/components/LabelToIdTable.tsx, src/styles/components/_index.scss, src/styles/components/_labelToId.scss, src/styles/components/_labelToIdTable.scss
resolved #138 
DatasetやThresholdをセットする箇所もレイアウトの調整が入っていたようなので、一緒に対応しました。
（背景色が薄いので分かりにくいですが、枠に白背景が設定されました）
=> #138対応：LabelToIdTable調整

auto-imports.d.ts, next.config.mjs, package.json, src/components/Datasets.tsx, src/components/Explore.tsx, src/components/IdInput.tsx, src/pages/index.tsx, src/styles/_index.scss, yarn.lock
routerのqueryにrouteを指定できるようにする
初期ロードが終わらないときに重くなる問題を修正
datasetsの検索を修正
=> queryにrouteを持つ

src/components/LabelToId.tsx, src/styles/components/_labelToId.scss
=> LABEL2ID：インフォメーションツールチップを追加

src/components/ResultModalAction.tsx, src/styles/_modal.scss, src/styles/foundation/_common.scss
=> #157対応：スイッチボタンの追加

src/components/LabelToIdTable.tsx, src/styles/components/_labelToIdTable.scss
=> #171対応：Label To Id テーブルのthのIDにセレクト追加

src/styles/foundation/_common.scss
- resolved #176
改行が発生して、高さが変わっても崩れないよう修正しました。
=> #176対応：トグルボタンの修正

src/components/ResultModalAction.tsx, src/components/ResultModalActionTable.tsx, src/hooks/useResultModalPreview.ts
previewのmode変更時にapi callするようにします
=> previewの挙動を修正する

src/components/ResultModal.tsx, src/styles/_modal.scss
resolved #205 
横スクロールが発生しないように調整しました。
下のスクショは内容は同一のものですが、画面幅が異なる状態のスクショです。
| 画面幅：大 | 画面幅：小 |
| --- | --- |
| ![screencapture-localhost-3000-2025-03-26-13_22_39](https://github.com/user-attachments/assets/9b94a146-5284-4430-b2b9-326be4e6c9da) | ![screencapture-localhost-3000-2025-03-26-13_23_00](https://github.com/user-attachments/assets/5e6bb08e-4746-4d00-933d-c469bef67e59) |
=> #205対応中：ResultsのRouteの表示改善

src/components/ResultModalActionTable.tsx, src/styles/_modal.scss
=> #211対応：Resultsモーダルの中のPreviewテーブルのth内のチェックボックスを整える

src/components/ResultModalActionTable.tsx, src/styles/_modal.scss
=> #223対応：Resultsモーダルのテーブルヘッダー内のレイアウト調整

src/components/ResultModalActionTable.tsx, src/styles/_modal.scss
https://github.com/togoid/togoid-converter/issues/189#issuecomment-2899897820
また調整が必要でしたら、お気軽にお声がけください。
=> Labelのチェックボックスの調整

src/lib/setting.ts
=> update category color

swagger/oas.json
=> Fixed mismatches between the spec and the implementation.
